name 'tomcant'
maintainer 'Tom Cant'
maintainer_email 'tomcant@gmail.com'
license 'All rights reserved'
description 'Configures a server for hosting a personal website'
version '0.0.1'
depends 'fb_apt'
